---
title: "20210316 Games"
author: "Jeremy Allen"
date: "3/16/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

library(tidyverse)
library(tidytext)

get_sentiments("nrc")

data(stop_words)

nrc_types <- get_sentiments("nrc") %>% 
 pull(sentiment) %>% 
 unique()

nrc_joy <- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")
nrc_sad <- get_sentiments("nrc") %>% 
  filter(sentiment == "sadness")

stops <- stop_words %>% 
 bind_rows(tibble(
  word = c("edition", "online", "ii", "iii", "iv", "vi", "vii",
           "viii", "ix", "definitive", "remastered"),
  lexicon = c(rep("jda", 11))
 ))

```

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

games <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-16/games.csv')

```

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

# function to get emotion words and output as list of two types
get_emotion_words <- function(x) {
 
   name <- as_tibble(x) %>% 
   rename(gamename = value) %>% 
   count(gamename) %>% 
   mutate(gamename = str_remove_all(gamename, "<U.....>")) %>% 
   select(-n) %>%
   unnest_tokens(
    output = word,
    input = gamename,
    token = "words",
    to_lower = TRUE,
    strip_punct = TRUE
   ) %>%
   anti_join(stops) %>% 
   filter(
    nchar(word) > 1,              # must be more than one character
    str_detect(word, "^[a-z]"),   # must start with a letter
    str_detect(word, "[a-z]")     # must not be only numbers
   ) %>% 
   count(word, sort = TRUE) %>%
   mutate(word = reorder(word, n))

  emotion_words <- list(
   joy = name %>% inner_join(nrc_joy),
   sad = name %>% inner_join(nrc_sad)
  )

emotion_words

}

name_emotions <- games %>%
 filter(year > 2014 & year < 2021) %>% 
 group_by(year) %>% 
 summarise(sum_avg_players = sum(avg),
           emotion_words = get_emotion_words(gamename)) %>% 
 ungroup() %>%
 arrange(year)

emotions_scored <- name_emotions %>% 
 unnest(emotion_words) %>% 
 mutate(score = n*sum_avg_players) %>% 
 group_by(year, sentiment) %>% 
 summarise(valence = sum(score)) %>% 
 ungroup() %>% 
 mutate(sentiment = factor(sentiment, levels = c("sadness", "joy"), order = TRUE))



```

```{r}

p <- emotions_scored %>% ggplot(aes(x = sentiment, y = valence, fill = sentiment)) +
  geom_bar(stat = "identity", width = 1) +
  scale_fill_manual(values = c("#e600e6", "#625062"), breaks = c("joy", "sadness")) +
  labs(x = "",
       y = "",
       title = "Emotional Content of Words in Video Game Titles
In all years, game titles consisted of more sad words than joy words.",
       subtitle = "Emotional valence of words determined by the NRC Emotion Lexicon",
       caption = "Data source: SteamCharts | Data viz: @jeremy_data
Reference: Emotions Evoked by Common Words and Phrases: Using Mechanical Turk to Create an Emotion Lexicon, Saif Mohammad and Peter Turney, In Proceedings of the NAACL-HLT 2010 Workshop on Computational Approaches to Analysis and Generation of Emotion in Text, June 2010, LA, California.",
       fill = "") +
  coord_polar() +
  facet_wrap(~ year, ncol = 6) +
  theme_minimal() +
  theme(
   text = element_text(color = "#cfafcf"),
   strip.text = element_text(color = "#cfafcf"),
   plot.title = element_text(size = 22),
   plot.subtitle = element_text(size = 18, margin = margin(.5,0,3,0, unit = "cm")),
   legend.box.margin = margin(.25,0,2,0, unit = "cm"),
   legend.position = "top",
   legend.text = element_text(size = 16),
   legend.spacing.x = unit(1, 'cm'),
   legend.text.align = 0,
   panel.grid = element_blank(),
   axis.title.x = element_blank(),
   axis.title.y = element_blank(),
   axis.text.x = element_blank(),
   axis.text.y = element_blank(),
   plot.margin = margin(3,3,.5,3, unit = "cm"),
   plot.background = element_rect(fill = "black"),
   plot.caption = element_text(size = 10, margin = margin(3,0,0,0, unit = "cm"))
  ) 

ggsave("sad_games.png", plot = p, width = 24, height = 12, units = "in")

```

