---
title: "20210323 UN Votes"
author: "Jeremy Allen"
date: "3/23/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(here)
library(ggtext)
library(tidyverse)

```

```{r}

unvotes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/unvotes.csv')
roll_calls <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/roll_calls.csv')
issues <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/issues.csv')

```

```{r}
 
clean_rc <- roll_calls %>% 
  select(rcid, session, unres, short, descr, date, importantvote) %>% 
  mutate(rcid = as.character(rcid)) %>% 
  drop_na()

clean_votes <- unvotes %>% 
  select(rcid, country, vote) %>% 
  filter(country == "United States") %>% 
  mutate(rcid = as.character(rcid)) %>% 
  drop_na()
 
clean_us_votes <- clean_votes %>%
 semi_join(clean_rc, by = "rcid") %>% 
 left_join(clean_rc, by = "rcid")
 
```

```{r}

# clean_us_votes %>% 
#  group_by(short) %>% 
#  summarise(yes = )

dat <- clean_us_votes %>% 
 mutate(short = fct_lump_n(f = short, n = 10)) %>% 
 filter(short != "Other") %>% 
 count(short, vote) %>% 
 mutate(vote = factor(vote, levels = c("yes", "abstain", "no"), ordered = TRUE)) %>%
 arrange(short, vote) %>% 
 uncount(n)

my_levels <- dat %>% 
 count(short, vote) %>% 
 pivot_wider(names_from = "vote", values_from = "n", values_fill = 0) %>% 
 arrange(desc(yes)) %>% 
 pull(short)



```

```{r}

p <- dat %>% 
 mutate(short = factor(short, levels = my_levels, ordered = TRUE)) %>% 
 ggplot() +
 geom_dotplot(aes(x = short, fill = vote),
              color = "white",
              binaxis = "x",
              binwidth = .75,
              binpositions = "all",
              dotsize = .35,
              show.legend = FALSE,
              stackdir = "up",
              stackgroups = TRUE) +
 scale_fill_manual(values = c("yes" = "#46b9a2", "abstain" = "#999999", "no" = "#e05281")) +
 coord_flip() +
 #scale_y_discrete() +
 labs(
  title = "In the UN, which issues have no *yes-votes* from the United States?",
  subtitle = "<i style='color:#46b9a2;'>Yes</i> | <i style='color:#e05281;'>No</i> | <i style='color:#999999;'>Abstain</i>",
  x = NULL,
  y = NULL,
  caption = "Source: dataverse.harvard.edu | Dataviz: @jeremy_data | For the R for Data Science Online Learning Community"
 ) +
 theme(
  text = element_text(color = "#808080"),
  panel.grid = element_blank(),
  axis.ticks = element_blank(),
  axis.text.x = element_blank(),
  axis.text.y = element_markdown(face = "bold"),
  plot.background = element_rect(fill = "#ffffff", color = "#808080"),
  panel.background = element_rect(fill = "#ffffff"),
  plot.margin = margin(2,2,.25,2, unit = "cm"),
  plot.title = element_markdown(face = 'bold', size = 24, hjust = .5),
  plot.title.position = 'plot',
  plot.subtitle = element_markdown(face = 'bold', size = 16, margin = margin(.5,0,2,0, unit = "cm"), hjust = .5),
  plot.caption = element_markdown(size = 12, hjust = .5, margin = margin(1,0,0,0, unit = "cm")),
  plot.caption.position = 'plot'
 )
 
ggsave(here::here("20210323_un_votes", "votes.png"),
       p,
       device = "png",
       width = 13, height = 8,
       units = "in", dpi = 300,
       scale = 1)

```

